services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - WEBHOOK_TUNNEL_URL=https://${NGROK_DOMAIN}
      - N8N_HOST=${NGROK_DOMAIN}
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http --domain=${NGROK_DOMAIN} n8n:5678
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  n8n_data:
